[package]
name = "smcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
thiserror = "1.0.31"
tokio = "1.19.2"
serde_json = "1.0.82"